# Generated by Django 4.0.4 on 2022-06-01 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=64)),
                ('brand', models.CharField(choices=[('KTM', 'KTM'), ('YAMAHA', 'YAMAHA'), ('Ducati', 'Ducati'), ('Husqvarna', 'Husqvarna'), ('Aprilia', 'Aprilia'), ('MV Agusta', 'MV Agusta')], max_length=64)),
                ('engine_size', models.CharField(max_length=4)),
                ('year', models.CharField(choices=[('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010')], max_length=4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
